// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef ui_h
#define ui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include "gl_view.h"
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Browser.H>

class UserInterface {
public:
  UserInterface();
  Fl_Double_Window *mainWindow;
  glView *view;
  static Fl_Menu_Item menu_[];
  static Fl_Menu_Item *menuShowShadow;
private:
  void cb_menuShowShadow_i(Fl_Menu_*, void*);
  static void cb_menuShowShadow(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menuShowReflection;
private:
  void cb_menuShowReflection_i(Fl_Menu_*, void*);
  static void cb_menuShowReflection(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menuShowPreview;
private:
  void cb_menuShowPreview_i(Fl_Menu_*, void*);
  static void cb_menuShowPreview(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menuShowFPS;
private:
  void cb_menuShowFPS_i(Fl_Menu_*, void*);
  static void cb_menuShowFPS(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menuCameraFree;
private:
  void cb_menuCameraFree_i(Fl_Menu_*, void*);
  static void cb_menuCameraFree(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *menuCameraAuto;
private:
  void cb_menuCameraAuto_i(Fl_Menu_*, void*);
  static void cb_menuCameraAuto(Fl_Menu_*, void*);
public:
  Fl_Button *btn_play;
private:
  void cb_btn_play_i(Fl_Button*, void*);
  static void cb_btn_play(Fl_Button*, void*);
public:
  Fl_Value_Slider *m_slider;
private:
  void cb_m_slider_i(Fl_Value_Slider*, void*);
  static void cb_m_slider(Fl_Value_Slider*, void*);
  void cb_1refresh_i(Fl_Button*, void*);
  static void cb_1refresh(Fl_Button*, void*);
public:
  Fl_Spinner *edit_desired_fps;
private:
  void cb_edit_desired_fps_i(Fl_Spinner*, void*);
  static void cb_edit_desired_fps(Fl_Spinner*, void*);
public:
  Fl_Browser *m_browser_file;
private:
  void cb_m_browser_file_i(Fl_Browser*, void*);
  static void cb_m_browser_file(Fl_Browser*, void*);
  void cb_2_i(Fl_Button*, void*);
  static void cb_2(Fl_Button*, void*);
  void cb_Remove_i(Fl_Button*, void*);
  static void cb_Remove(Fl_Button*, void*);
public:
  Fl_Browser *m_browser_file_comb;
private:
  void cb__i(Fl_Button*, void*);
  static void cb_(Fl_Button*, void*);
  void cb_1_i(Fl_Button*, void*);
  static void cb_1(Fl_Button*, void*);
public:
  Fl_Button *radio_single;
private:
  void cb_radio_single_i(Fl_Button*, void*);
  static void cb_radio_single(Fl_Button*, void*);
public:
  Fl_Button *radio_mutliple;
private:
  void cb_radio_mutliple_i(Fl_Button*, void*);
  static void cb_radio_mutliple(Fl_Button*, void*);
public:
  Fl_Spinner *edit_num_blend_frames;
private:
  void cb_edit_num_blend_frames_i(Fl_Spinner*, void*);
  static void cb_edit_num_blend_frames(Fl_Spinner*, void*);
public:
  Fl_Box *lbl_blend_time;
  Fl_Box *lbl_name;
  Fl_Box *lbl_joints;
  Fl_Box *lbl_frames;
  Fl_Box *lbl_fps;
  Fl_Box *boxImageLogo;
  void show(int argc, char **argv);
  static void idleCB(UserInterface* gv);
};
#endif
